SET LINESIZE 500
SET PAGESIZE 1000
SET VERIFY OFF
SET TRIMOUT ON TRIMS ON

SELECT stale.TABLE_NAME, stale.OWNER, stale.NUM_ROWS, mod.INSERTS, mod.UPDATES, mod.DELETES, stale.SAMPLE_SIZE, stale.LAST_ANALYZED
FROM (SELECT TABLE_NAME, OWNER, NUM_ROWS, SAMPLE_SIZE, LAST_ANALYZED 
      FROM DBA_TAB_STATISTICS
      WHERE STALE_STATS = 'YES'
            AND OWNER NOT LIKE '%SYS%') stale,
     DBA_TAB_MODIFICATIONS mod
WHERE mod.TABLE_OWNER = stale.OWNER
      AND mod.TABLE_NAME = stale.TABLE_NAME
ORDER BY 2;
